<?php
/**
 * @package nativepdf
 * @link    https://github.com/Javaabu/nativepdf
 * @license http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License
 */
namespace NativePdf\Text;

/**
 * Lookup into the Unicode data tables generated by
 * bin/generate-unicode-data.php (lib/res/unicode/*.php).
 *
 * @package nativepdf
 */
final class UnicodeData
{
    /**
     * @var array|null
     */
    private static $bidiClasses;

    /**
     * @var array|null
     */
    private static $mirror;

    /**
     * @var array|null
     */
    private static $brackets;

    /**
     * @var array|null
     */
    private static $joining;

    /**
     * @var array|null
     */
    private static $arabicForms;

    /**
     * @param string $file
     * @return array
     */
    private static function load(string $file): array
    {
        return require __DIR__ . "/../../lib/res/unicode/" . $file;
    }

    /**
     * Binary search a sorted list of [start, end, value] ranges.
     *
     * @param array $ranges
     * @param int   $cp
     * @return mixed|null The value, or null if no range contains $cp
     */
    private static function rangeLookup(array $ranges, int $cp)
    {
        $lo = 0;
        $hi = count($ranges) - 1;

        while ($lo <= $hi) {
            $mid = ($lo + $hi) >> 1;
            $r = $ranges[$mid];

            if ($cp < $r[0]) {
                $hi = $mid - 1;
            } elseif ($cp > $r[1]) {
                $lo = $mid + 1;
            } else {
                return $r[2];
            }
        }

        return null;
    }

    /**
     * The Bidi_Class of a code point (UAX #9), e.g. "L", "R", "AL", "EN".
     *
     * @param int $cp
     * @return string
     */
    public static function bidiClass(int $cp): string
    {
        if (self::$bidiClasses === null) {
            self::$bidiClasses = self::load("bidi_classes.php");
        }

        $class = self::rangeLookup(self::$bidiClasses["assigned"], $cp);
        if ($class !== null) {
            return $class;
        }

        $class = self::rangeLookup(self::$bidiClasses["defaults"], $cp);

        return $class !== null ? $class : "L";
    }

    /**
     * The mirrored counterpart of a code point per BidiMirroring.txt, or
     * null if the character has no mirror.
     *
     * @param int $cp
     * @return int|null
     */
    public static function mirror(int $cp): ?int
    {
        if (self::$mirror === null) {
            self::$mirror = self::load("bidi_mirror.php");
        }

        return isset(self::$mirror[$cp]) ? self::$mirror[$cp] : null;
    }

    /**
     * Paired-bracket info per BidiBrackets.txt: [pairedCp, "o"|"c"], or
     * null.
     *
     * @param int $cp
     * @return array|null
     */
    public static function bracket(int $cp): ?array
    {
        if (self::$brackets === null) {
            self::$brackets = self::load("bidi_brackets.php");
        }

        return isset(self::$brackets[$cp]) ? self::$brackets[$cp] : null;
    }

    /**
     * The Joining_Type of a code point (per DerivedJoiningType.txt):
     * "R", "L", "D", "C", "T", or "U".
     *
     * @param int $cp
     * @return string
     */
    public static function joiningType(int $cp): string
    {
        if (self::$joining === null) {
            self::$joining = self::load("joining_types.php");
        }

        $type = self::rangeLookup(self::$joining, $cp);

        return $type !== null ? $type : "U";
    }

    /**
     * The Arabic presentation forms of a base character:
     * [isolated, final, initial, medial], entries possibly null. Returns
     * null if the character has no presentation forms.
     *
     * @param int $cp
     * @return array|null
     */
    public static function arabicForms(int $cp): ?array
    {
        if (self::$arabicForms === null) {
            self::$arabicForms = self::load("arabic_forms.php");
        }

        return isset(self::$arabicForms["forms"][$cp])
            ? self::$arabicForms["forms"][$cp]
            : null;
    }

    /**
     * The lam-alef ligature forms [isolated, final] for lam followed by the
     * given alef variant, or null.
     *
     * @param int $alef
     * @return array|null
     */
    public static function lamAlefLigature(int $alef): ?array
    {
        if (self::$arabicForms === null) {
            self::$arabicForms = self::load("arabic_forms.php");
        }

        return isset(self::$arabicForms["ligatures"][$alef])
            ? self::$arabicForms["ligatures"][$alef]
            : null;
    }
}
